language: python

matrix:
  include:
    - os: linux
    - os: osx

before_install:
  - wget https://raw.githubusercontent.com/python/cpython/master/Tools/ssl/make_ssl_data.py
  - ls
  - |
  # clang complains about unused-parameter a lot, redirect stderr
- openssl version
